name: psychology_test_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider:
  firebase_core: ^2.27.1
  equatable: ^2.0.5
  bloc: ^8.1.3
  firebase_auth: ^4.17.9
  flutter_bloc: ^8.1.4
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito.ttf
        - asset: assets/fonts/nunito_medium.ttf
        - asset: assets/fonts/nunito_semibold.ttf
        - asset: assets/fonts/nunito_bold.ttf
